version: '2'
services:
    techfile-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/techfile/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=techfile
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
